// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOl_360AmLWZ0GCM5nJvpcxdKAn5l86kc',
    appId: '1:961240146342:web:16d2c3c8ca7a7724efaf67',
    messagingSenderId: '961240146342',
    projectId: 'app-pencatatan-keuangan',
    authDomain: 'app-pencatatan-keuangan.firebaseapp.com',
    storageBucket: 'app-pencatatan-keuangan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq4npx-YfbjCaiErD7F5gNUJzCBuQiPDA',
    appId: '1:961240146342:android:e5803c25852a6fcdefaf67',
    messagingSenderId: '961240146342',
    projectId: 'app-pencatatan-keuangan',
    storageBucket: 'app-pencatatan-keuangan.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOl_360AmLWZ0GCM5nJvpcxdKAn5l86kc',
    appId: '1:961240146342:web:af6ba25248f37f29efaf67',
    messagingSenderId: '961240146342',
    projectId: 'app-pencatatan-keuangan',
    authDomain: 'app-pencatatan-keuangan.firebaseapp.com',
    storageBucket: 'app-pencatatan-keuangan.firebasestorage.app',
  );
}
